SELECT PLOT.PLOTID, PLANT.PLANTVARIETY, COUNT(*) AS NUM_PRODUCTS
FROM PLOT
JOIN OPERATION OP ON OP.PLOTID = PLOT.PLOTID
JOIN INSTALLEDCROP IC ON IC.OPERATIONID = OP.OPERATIONID
JOIN CROP ON CROP.CROPID = IC.CROPID
JOIN PLANT ON PLANT.PLANTVARIETY = CROP.PLANTVARIETY
WHERE PLOT.PLOTID = 107 AND OP.OPERATIONDATE BETWEEN DATE '2010-01-01' AND DATE '2020-12-31'
GROUP BY PLOT.PLOTID, PLANT.PLANTVARIETY
ORDER BY PLANT.PLANTVARIETY ASC;