@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title USLP02 - System Sequence Diagram (SSD)

autonumber

actor "Product Owner" as ProductOwner
participant ":System" as System

activate ProductOwner

    ProductOwner -> System: asks to see the irrigation system controller simulation.
    activate System

        System --> ProductOwner: asks the user to import a file with the irrigation plan or imports a file by default.
    deactivate System

    ProductOwner -> System: chooses the desired option related to the file with the irrigation plan data.
    activate System

        System --> ProductOwner: asks the user to input a date/time slot to check if the system is on or asks if the user wants to check the system's current status.
    deactivate System

    ProductOwner -> System: chooses the desired option related to the date/time slot.
    activate System

        System --> ProductOwner: shows the system's status for the chosen date/time slot and the plot that is currently being irrigated.
    deactivate System

deactivate ProductOwner

@enduml