SELECT PLOT.PLOTID, PF.PRODUCTIONFACTORTYPE, COUNT(*) AS NUM_PROD_FACTORS
FROM PLOT
JOIN OPERATION OP ON OP.PLOTID = PLOT.PLOTID
JOIN PRODUCTIONFACTOROPERATION PFO ON PFO.OPERATIONID = OP.OPERATIONID
JOIN PRODUCTIONFACTOR PF ON PF.DESIGNATION = PFO.DESIGNATION
WHERE PLOT.PLOTID = 107 AND OP.OPERATIONDATE BETWEEN DATE '2010-01-01' AND DATE '2020-12-31'
GROUP BY PLOT.PLOTID, PF.PRODUCTIONFACTORTYPE
ORDER BY PF.PRODUCTIONFACTORTYPE ASC;